import './style.css'

const list = [
  "How is your day going on a scale of 1-5? (Everyone shows a number on their hand at once)",
  "What is a future hobby you would like to start?",
  "What was your first car?",
  "If you could relive any year of your life, which one would it be?",
  "What's your go-to karaoke song?",
  "If you are stuck at an airport with no wifi for 6 hours, how will you pass the time?",
  "Who is a non-family member that impacted you greatly as a kid?",
  "How would you describe your work to a child?",
  "What's a movie you'd want to rewatch?",
  "Name one person you are close to whom you'd like to be more like, and why",
  "What do people closest to you say is your best characteristic?",
  "When you were eight years old, what did you want to be when you grew up?",
  "What part of adulting is least natural for you?",
  "What have you changed your mind about in the past 6 months?",
  "Describe your morning routine",
  "What was your favorite meal growing up?",
  "How many cities have you lived in?",
  "What is your favorite condiment/spice?",
  "What is a favorite smell?",
  "What's the best thing about where you grew up?",
  "How did you learn to ride a bicycle?",
  "If you could travel anywhere for only one minute, where would you go?",
  "If you ended today only accomplishing one thing, what do you hope it is?",
  "Is there a law that you'd be excited to break?",
  "What do you miss most about childhood?",
  "What's the background on your laptop or phone?",
  "Which superhuman power is overrated?",
  "What is the best reward anyone can give you?",
  "Name one thing that you couldn't go a week without",
  "You've got $20 and can walk out of a grocery store with no guilt. What do you pick?",
  "When do you most feel older than you are?",
  "When do you most feel younger than you are? ",
  "What's a game that you'd likely win if you played against everyone on this call?",
  "What's your favorite weather season where you live?",
  "If your last meeting of the day got cancelled, how would you spend the time?",
  "If you could get the phone number of any celebrity, whom would you choose?",
  "If you were the hero in a story, what would be the tragic flaw you would have to overcome?",
  "If you could get tickets to any event in the world (past, present, or future), what would it be?",
  "Do you have a favorite quote?",
  "What is your favorite time of day?",
  "I wish everyone would ____",
  "Would you rather live 100 years in the past, or 100 years in the future?",
  "If you were to perform in the circus, what would you do?",
  "Do you plan your days off, or just let them flow?",
  "Is there a story behind your name?",
  "What's something you are thankful for today?",
  "What is something you think the group would be surprised to learn about you?",
  "What do you pack first when going on a trip?",
  "What's a significant idea you've read/listened to in the last month?",
  "If you were alone in your home and there was a fire, what would you grab on your way out? ",
  "What's an assumption most people make about you?",
  "When's the last time you felt fully rested?",
  "What was a recent memorable meal?",
  "What was the most unusual food you have ever eaten?",
  "If you had to move out of your country, where would you go?",
  "If you could live somewhere for one month with your expenses paid, where would you go?",
  "What language have you always wanted to learn?",
  "How many languages do you speak?",
  "What was the farthest you have ever traveled?",
  "What Olympic sport would you love to compete in (assuming you had trained and qualified for it)?",
  "If you were on a professional sports team, what number would you wear on your uniform?",
  "What hobbies did you have 10 years ago?",
  "What's a sport that you don't understand the rules to?",
  "Who is the hardest person you know to buy a gift for? ",
  "What's a company/brand that you love to follow?",
  "What do you consider to be the coolest job/career?",
  "What's the coolest thing you could pull out of a cereal/crackerjack box?",
  "What's a subject/topic that you'd like to teach others about?",
  "What makes a 'good day' for you?",
  "Have you ever started a business? If not, have you ever wanted to?",
  "What's something you admire about someone you don't like?",
  "Are you more likely to overplan or underplan a party?",
  "What's something that will become obsolete in ten years?",
  "What do you hope is the top Google result for your name?",
  "If you could have written any book, what book would you like to have written?",
  "What's a book you want to reread?",
  "If you could pick intro music to be played every time we did a roll call, what would you want?",
  "Say something nice to the person on your right.",
  "Your favorite ice cream flavor?",
  "Ocean, desert, mountains, forest?",
  "What do you wish that people would take more seriously? Less seriously?",
  "What's a question you hate being asked?",
  "If you had a catchphrase, what would it be?",
  "What's your favorite piece of clothing you own?",
  "What kind of music were you into 10 years ago?",
  "What's the last place you went to for the first time?",
  "Share a favorite family tradition?",
  "What was the first significant thing you remember buying with your own money?",
  "What nearly always makes you smile?",
  "Do you have a favorite charity you wish more people knew about?",
  "Do you have any phobias you’d like to break?",
  "Do you collect anything?",
  "What is worth waking up early for?",
  "What could you do without right now?",
  "if your life story was told, what medium would it be in?",
  "What were you really into when you were a kid?",
  "What has been the highlight of your week so far?",
  "What pet did you have or want to have as a kid?",
  "What's the most beautiful place within 20 miles of where you live?",
  "What's the most draining part about your work life? Most energizing?",
  "Who's a teacher you'll always remember?",
  "What's a tell that you are stressed out AND/OR super happy?",
  "What do you do to recharge?",
  "What's something that suddenly reminds you of your hometown?",
  "What's a book you would give to everyone you work with?",
  "What's the special meal your grandmother would make for you? (or some other special adult in your life)",
  "Who is your oldest friend, i.e. someone you consider a friend, but is quite old?",
  "Who is your youngest friend, i.e. someone you consider a friend, but is quite young?",
  "What's your favorite splurge item?"
];
// "Is there a law that you'd be excited to break?",
// "What is the best reward anyone can give you?",
// "Do you collect anything?",
// "What's the most beautiful place within 20 miles of where you live?",
// "What do you do to recharge?",
// "What has been the highlight of your week so far?",
// "What was the farthest you have ever traveled?",
//  "What's something that will become obsolete in ten years?"
// "What have you changed your mind about in the past 6 months?",
// "What's the best thing about where you grew up?",
// "What’s the most interesting thing you’ve read or seen lately?",
// "If you could have any superpower, what would it be and why?",
// "What’s a skill you’ve always wanted to learn but haven’t yet?",
// "If you could travel anywhere right now, where would you go?",
// "What’s your favorite way to relax after a long day?",
// "What’s the best advice you’ve ever gotten?",
// "What’s one thing on your bucket list that you really want to do?",
// "If you could only eat one meal for the rest of your life, what would it be?",
// "What’s a hobby or interest you love that others might not know about?",
// "What has been the highlight of your week so far?",
// "Your favorite ice cream flavor?",
// "What's a company/brand that you love to follow?",
// "What makes a 'good day' for you?",
// "Who is the hardest person you know to buy a gift for?",
// "What's a subject/topic that you'd like to teach others about?"
//"If you could meet any historical figure, who would it be and why?",

function random() {
    return Math.floor(Math.random() * 9);
}

document.getElementById("btn")!.addEventListener("click", () => {
  const qns = list;
  const item = random();
  console.log("clicked", item)
  document.getElementById("qn")!.innerText = qns[item];
})